# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [1]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [2]:
import numpy as np

arr = np.random.randint(-1000, 1000, size=(10,10))

print(arr)

print("\nMin - " + str(np.min(arr)))
print("Max - " + str(np.max(arr)))

[[-126  985   85  629   82  811 -473  -59 -996 -470]
 [ 177 -521 -568 -339 -230  370  -91 -172  -37 -490]
 [ 986 -528 -981  363  -69  817  996 -794   58  630]
 [ 679  730  801   54  145   97  693  124   13  447]
 [ 665 -953 -569 -480 -224  843 -837  476 -547  281]
 [-603 -353 -933  632 -434  666  583 -197  520 -576]
 [-932 -810 -408  -11 -391   -5 -114  978 -375  938]
 [-137 -114  900  157 -135 -275  448  753 -746  -38]
 [ 517 -912  618  315 -182 -695  862  981 -822 -485]
 [-838 -405 -473  556  675  885 -915 -481  121 -551]]

Min - -996
Max - 996


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [3]:
import numpy as np

size = 8

arr = np.zeros((size,size))

for i in range(size):
  for j in range(size):
    if i % 2 != 0 and j % 2 != 0:
      continue
    if i % 2 != 0 or j % 2 != 0:
      arr[i,j] = 1

print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [4]:
import numpy as np

z = np.arange(11)

print("Исходный массив:" + str(z))

for i in range(z.size):
  if z[i] > 3 and z[i] < 8:
    z[i] *= -1

print("Итоговый массив:" + str(z))

Исходный массив:[ 0  1  2  3  4  5  6  7  8  9 10]
Итоговый массив:[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [5]:
import numpy as np

z = np.random.rand(5, 10)
average = np.mean(z, axis=1, keepdims=True)

print("Исходный массив\n" + str(z))
print("\nСреднее арифметическое\n" + str(average) + "\n")

print("Итоговый массив: \n" + str(np.subtract(z, average)))

Исходный массив
[[0.40214821 0.39919269 0.53451435 0.49622475 0.20450629 0.18380329
  0.28945636 0.59239893 0.69492234 0.98581528]
 [0.52249544 0.28098382 0.32823649 0.717611   0.587133   0.27074246
  0.29496452 0.71289859 0.19947077 0.22609594]
 [0.47530316 0.61428974 0.384742   0.9368664  0.47964769 0.49865953
  0.85523281 0.23539789 0.87849972 0.49730722]
 [0.91377382 0.10833002 0.37622341 0.71855204 0.60195032 0.06617603
  0.57417501 0.28144111 0.36349783 0.9995784 ]
 [0.133824   0.69075699 0.08564896 0.7418571  0.48146483 0.4199697
  0.86891623 0.95768402 0.31421389 0.35646743]]

Среднее арифметическое
[[0.47829825]
 [0.4140632 ]
 [0.58559461]
 [0.5003698 ]
 [0.50508032]]

Итоговый массив: 
[[-0.07615004 -0.07910556  0.05621611  0.0179265  -0.27379196 -0.29449496
  -0.18884189  0.11410068  0.21662409  0.50751703]
 [ 0.10843223 -0.13307939 -0.08582671  0.3035478   0.1730698  -0.14332074
  -0.11909868  0.29883539 -0.21459243 -0.18796727]
 [-0.11029146  0.02869513 -0.20085262  0.3512

5. Поменяйте 1 и 2 строки матрицы

In [6]:
import numpy as np

z = np.arange(25).reshape(5,5)
print("Исходное:\n" + str(z))

tmp = z[0][:].copy()
z[0][:] = z[1][:]
z[1][:] = tmp

print("\nИтог:\n" + str(z))

Исходное:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Итог:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [7]:
import numpy as np
import math

z = np.random.random((10,2))
res = z.copy()

res[:, 0] = np.sqrt(np.square(z[:, 0]) + np.square(z[:, 1]))
res[:, 1] = np.arctan2(z[:, 1], z[:, 0])

print("Исходное:\n", z)
print("\nРезультат (r, theta):\n", res)

Исходное:
 [[0.81231803 0.44312826]
 [0.45963306 0.67293191]
 [0.34985913 0.81746657]
 [0.21675015 0.57312379]
 [0.78171643 0.76688446]
 [0.38500076 0.69053263]
 [0.37672003 0.99260012]
 [0.03274081 0.91393362]
 [0.53463466 0.46322298]
 [0.91226325 0.90440443]]

Результат (r, theta):
 [[0.92532331 0.49939008]
 [0.81492326 0.97155027]
 [0.88918671 1.16640452]
 [0.61274098 1.20923117]
 [1.09507641 0.77582079]
 [0.79060793 1.06218136]
 [1.06168403 1.20806139]
 [0.91451988 1.53498759]
 [0.70739646 0.71395497]
 [1.28459006 0.78107223]]


7. Заменить максимальный элемент массива на ноль

In [8]:
import numpy as np

z = np.random.random(10)
max = z.max()

print("Максимум:", max)
print("\nИсходное:\n", z)

z[(np.where(z == max))] = 0

print("\nРезультат:\n", z)

Максимум: 0.9619139876615996

Исходное:
 [0.89025422 0.01005982 0.65807448 0.96191399 0.67184368 0.78834441
 0.41797959 0.0097624  0.25756791 0.56948853]

Результат:
 [0.89025422 0.01005982 0.65807448 0.         0.67184368 0.78834441
 0.41797959 0.0097624  0.25756791 0.56948853]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [9]:
import numpy as np

z = np.ones(10)
i = np.random.randint(0,len(z),20)
chk = ""

print("Первый массив:\n", z)
print("\nВторой массив:\n", i)

for char in i:
  if str(char) in chk:
    continue
  else:
    z[char] += 1
    chk += str(char)

print("\nРезультат:\n", z)

Первый массив:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Второй массив:
 [5 9 3 3 4 5 1 8 7 5 2 2 6 0 6 0 2 8 6 8]

Результат:
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [11]:
import numpy as np

z = np.array([1,2,3,4,5])
result = []

for i in range(z.size - 1):
    result.append(int(z[i]))
    result.append(0)
    result.append(0)
    result.append(0)

result.append(int(z[z.size-1]))

arr = np.array(result)
print("Исходное:\n", z)
print("\nРезультат:\n", result)

Исходное:
 [1 2 3 4 5]

Результат:
 [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [10]:
import numpy as np

z = np.arange(100)
v = np.random.uniform(0,100)
chk = v - int(v)

print("Массив:\n", z)
print("Исходное число:\n", v)

print((z[int(v)], z[int(v) + 1])[chk > 0.5])

Массив:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Исходное число:
 5.606841666906382
6


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?